### ISSUE TITLE
static directory / bcuploader.js file does not exist

### ISSUE THREAD

**Issue by joegaper** [BrightcoveOS/evaporate-brightcove#25]
followed the set up instructions. static folder and bcuploader.js file do not exist. my example doesn't work at all. my version of node is v.8.9.2. am i missing something?

**Comment by brycefisher** [comment]
@joegaper -- you are :100: correct. I let you down by not providing accurate setup information -- I'm so sorry!

Here's how to actually get setup and working using the example code (apologies the steps are so involved):

```
git clone https://github.com/BrightcoveOS/evaporate-brightcove.git
cd evaporate-brightcove/examples/nodejs
npm install
cd ../..
npm install
cp .env-sample .env
vim .env  # Replace dummy credentials with real values
npm start
```

Apparently, the frontend code needs to be built the first time using `npm start`, but once you've done that the first time, use `npm run watch` so that your changes are automatically noticed and nodemon will restart the nodejs server process with your changes.

**Comment by joegaper** [comment]
thanks bryce, running npm start in the root runs webpack, and all looks well in the world. cheers.
